name: "Set up Linter"
description: "Set up Linter"

runs:
  using: "composite"
  steps:
    - name: Install Poetry
      shell: bash
      run: pipx install poetry==1.8.3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "poetry"

    - name: Install dependencies
      shell: bash
      run: |
        poetry env use 3.10
        poetry install --with dev

    - name: Set up Reviewdog
      uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest
